name: onedrive-cli 
base: core24
adopt-info: onedrive
summary: Free OneDrive Client for Linux 
description: |
  A free Microsoft OneDrive Client which supports OneDrive Personal, OneDrive for Business, OneDrive for Office365 and SharePoint.


  Please note that this is not an officially maintained package. Use at your own risk.

platforms:
  amd64:
  arm64:

grade: stable
confinement: strict

apps:
  onedrive-cli:
    command: usr/local/bin/onedrive
    completer: usr/local/bin/complete.bash
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/lib
    plugs:
      - network
      - home
      - desktop

parts:
  curl:
    plugin: autotools
    source: .
    override-pull: |
      wget $(wget -q -O - https://api.github.com/repos/curl/curl/releases/latest  |  jq -r '.assets[] | select(.name | endswith (".tar.gz")) | .browser_download_url') -O curl-src.tar.gz
      tar zxf curl-src.tar.gz --strip-components=1
      rm -f curl-src.tar.gz
    autotools-configure-parameters:
      - --with-openssl
      - --with-nghttp2
      - --enable-versioned-symbols
    build-packages:
      - wget
      - jq
      - libssl-dev
      - nghttp2
      - libnghttp2-dev
      - libpsl-dev
    stage-packages:
      - libnghttp2-14
      - libpsl5t64

  onedrive:
    after: [curl]
    plugin: autotools
    source-type: git
    source: https://github.com/abraunegg/onedrive
    source-tag: 'v2.5.6'
    source-depth: 1
    build-packages:
      - ldc
      # - libcurl4-openssl-dev
      - libsqlite3-dev
      - pkg-config
      - libnotify-dev
      - libdbus-1-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | tr -d 'v')
      # keep bash completion file, change completion name from 'onedrive' to 'onedrive-cli'
      mkdir -p $CRAFT_PART_INSTALL/usr/local/bin/
      sed 's/onedrive/onedrive-cli/g' $CRAFT_PART_SRC/contrib/completions/complete.bash > $CRAFT_PART_INSTALL/usr/local/bin/complete.bash
    autotools-configure-parameters:
      - --enable-notifications
    stage-packages:
      #- libcurl4t64
      - libphobos2-ldc-shared106
      - libgdk-pixbuf-2.0-0
      - libjpeg-turbo8
      - libnotify4
      - libdbus-1-3
    prime:
      - -lib
      - -usr/lib/systemd
      - -usr/local/etc
      - -usr/local/share
